"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 illustration.gltf --transform 
Files: illustration.gltf [5.93MB] > illustration-transformed.glb [3.76MB] (37%)
Author: ganzhugav (https://sketchfab.com/ganzhugav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colourdraftssimon-stalenhag-scene-8728b0b42c4e4fd7889d34a76966def1
Title: colourdrafts(Simon Stalenhag scene)
*/

import { useGLTF } from "@react-three/drei";

export default function Illustration(props) {
  const { nodes, materials } = useGLTF("/gltf/illustration-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[0, -0.1, 0.2]}
    >
      <mesh
        geometry={nodes.polySurface282_lambert2_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0.002, 0.069, -0.079]}
        rotation={[0, 0, -0.069]}
        scale={[0.093, 0.04, 0.004]}
      />
      <mesh
        geometry={nodes.polySurface882_lambert30_0.geometry}
        material={materials.PaletteMaterial002}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface2534_blinn2_0.geometry}
        material={materials.PaletteMaterial003}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface2547_blinn1_0.geometry}
        material={materials.PaletteMaterial004}
        position={[-0.008, -0.032, 0.045]}
        rotation={[0, 0.047, 0]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.polySurface3025_blinn3_0.geometry}
        material={materials.PaletteMaterial005}
        position={[0.002, 0, 0.002]}
        rotation={[0, 0, 0.021]}
        scale={0.01}
      />
      <instancedMesh
        args={[
          nodes.polySurface853_lambert28_0.geometry,
          materials.PaletteMaterial001,
          8,
        ]}
        instanceMatrix={nodes.polySurface853_lambert28_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.pCube133_lambert28_0.geometry,
          materials.PaletteMaterial001,
          8,
        ]}
        instanceMatrix={nodes.pCube133_lambert28_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface1064_lambert28_0.geometry,
          materials.PaletteMaterial001,
          23,
        ]}
        instanceMatrix={nodes.polySurface1064_lambert28_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface1122_lambert5_0.geometry,
          materials.PaletteMaterial001,
          7,
        ]}
        instanceMatrix={nodes.polySurface1122_lambert5_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface1122_lambert38_0.geometry,
          materials.PaletteMaterial001,
          7,
        ]}
        instanceMatrix={nodes.polySurface1122_lambert38_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface1128_lambert5_0.geometry,
          materials.PaletteMaterial001,
          7,
        ]}
        instanceMatrix={nodes.polySurface1128_lambert5_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface1128_lambert38_0.geometry,
          materials.PaletteMaterial001,
          7,
        ]}
        instanceMatrix={nodes.polySurface1128_lambert38_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.pCube179_lambert28_0.geometry,
          materials.PaletteMaterial001,
          6,
        ]}
        instanceMatrix={nodes.pCube179_lambert28_0.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/gltf/illustration-transformed.glb");
